# Generated by Django 5.2.7 on 2025-11-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('domicilio_calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('domicilio_numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('domicilio_colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('domicilio_ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('domicilio_estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('domicilio_pais', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('domicilio_cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
