# Generated by Django 5.2.7 on 2025-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.CharField(default='601', max_length=10, verbose_name='Régimen Fiscal'),
        ),
    ]
