# Generated by Django 5.2.7 on 2025-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocuentaporcobrar',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago de Cuenta por Cobrar', 'verbose_name_plural': 'Pagos de Cuentas por Cobrar'},
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='fecha',
            field=models.DateField(),
        ),
    ]
