# Generated by Django 5.2.7 on 2025-11-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujocaja', '0002_movimientobancario'),
        ('ventas', '0002_alter_pagocuentaporcobrar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentaporcobrar',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujocaja.cuentabancaria', verbose_name='Cuenta Bancaria'),
        ),
    ]
