# Generated by Django 5.2.7 on 2025-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pagocuentaporcobrar_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='cadena_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='fecha_timbrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='folio_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='pdf_timbrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='xml_timbrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
