# Generated by Django 5.2.7 on 2025-11-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_facturaventa_cadena_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventa',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones', null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones', null=True),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones', null=True),
        ),
    ]
