# Generated by Django 5.2.7 on 2025-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cotizacionventa_notas_facturaventa_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
    ]
