# Generated by Django 5.2.7 on 2026-07-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionventa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.vendedor'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.vendedor'),
        ),
        migrations.AddField(
            model_name='pedidoventa',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.vendedor'),
        ),
    ]
