# Generated by Django 5.2.7 on 2025-10-19 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Material',
                'verbose_name_plural': 'Categorías de Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo (kg)'), ('g', 'Gramo (g)'), ('lt', 'Litro (lt)'), ('ml', 'Mililitro (ml)'), ('m', 'Metro (m)'), ('cm', 'Centímetro (cm)'), ('m2', 'Metro cuadrado (m²)'), ('m3', 'Metro cúbico (m³)'), ('h', 'Hora (h)'), ('día', 'Día'), ('caja', 'Caja'), ('rollo', 'Rollo'), ('paquete', 'Paquete'), ('servicio', 'Servicio')], max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('es_inventariable', models.BooleanField(default=True, verbose_name='¿Es inventariable?')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock mínimo')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.categoriamaterial')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
    ]
