# Generated by Django 5.2.7 on 2025-10-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_almacen_stockalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='aplica_iva',
            field=models.BooleanField(default=False, verbose_name='¿Aplica IVA?'),
        ),
    ]
