# Generated by Django 5.2.7 on 2025-12-03 15:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_material_aplica_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalmacen',
            name='cantidad_danada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockalmacen',
            name='cantidad_reservada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockalmacen',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_compra', 'Entrada por Compra'), ('entrada_devolucion_venta', 'Devolución de Venta'), ('entrada_ajuste_positivo', 'Ajuste Positivo'), ('salida_venta', 'Salida por Venta'), ('salida_devolucion_compra', 'Devolución a Proveedor'), ('salida_ajuste_negativo', 'Ajuste Negativo'), ('transferencia', 'Transferencia entre Almacenes'), ('conteo_fisico', 'Conteo Físico')], max_length=50)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='materiales.almacen')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='materiales.almacen')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Almacén',
                'verbose_name_plural': 'Movimientos de Almacén',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.material')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='materiales.movimientoalmacen')),
            ],
        ),
    ]
