# Generated by Django 5.2.7 on 2025-12-03 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_stockalmacen_cantidad_danada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
