# Generated by Django 5.2.7 on 2026-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_movimientoalmacen_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='tipo',
            field=models.CharField(choices=[('entrada_compra', 'Entrada por Compra'), ('entrada_devolucion_venta', 'Devolución de Venta'), ('entrada_ajuste_positivo', 'Ajuste Positivo'), ('salida_venta', 'Salida por Venta'), ('salida_devolucion_compra', 'Devolución a Proveedor'), ('salida_ajuste_negativo', 'Ajuste Negativo'), ('transferencia', 'Transferencia entre Almacenes'), ('conteo_fisico', 'Conteo Físico'), ('salida_taller', 'Salida por Consumo en Taller')], max_length=50),
        ),
    ]
