# Generated by Django 5.2.7 on 2025-11-21 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('pais', models.CharField(default='México', max_length=50)),
                ('swift', models.CharField(blank=True, help_text='Código SWIFT para transferencias internacionales', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('clabe', models.CharField(blank=True, help_text='CLABE interbancaria (México)', max_length=18)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('inversion', 'Cuenta de Inversión')], max_length=20)),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Americanos'), ('EUR', 'Euros')], default='MXN', max_length=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción de la cuenta')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='flujocaja.banco')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['banco__nombre', 'numero_cuenta'],
            },
        ),
    ]
