# Generated by Django 5.2.7 on 2025-11-21 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujocaja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('tipo_documento', models.CharField(choices=[('factura_venta', 'Factura de Venta'), ('factura_compra', 'Factura de Proveedor'), ('cobro_cliente', 'Cobro Cliente'), ('pago_proveedor', 'Pago Proveedor'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], max_length=20)),
                ('documento_id', models.PositiveIntegerField(blank=True, null=True)),
                ('documento_numero', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('conciliado', 'Conciliado'), ('cancelado', 'Cancelado')], default='registrado', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='flujocaja.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
