# Generated by Django 5.2.7 on 2025-10-24 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('tipo_cliente', models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], max_length=20)),
                ('rfc', models.CharField(max_length=20, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, max_length=20, verbose_name='CURP')),
                ('regimen_fiscal', models.CharField(choices=[('601', 'General de Ley Personas Morales'), ('603', 'Personas Morales con Fines no Lucrativos'), ('605', 'Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', 'Arrendamiento'), ('607', 'Régimen de Enajenación o Adquisición de Bienes'), ('608', 'Demás ingresos'), ('610', 'Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', 'Ingresos por Dividendos (socios y accionistas)'), ('612', 'Personas Físicas con Actividades Empresariales y Profesionales'), ('614', 'Ingresos por intereses'), ('615', 'Régimen de los ingresos por obtención de premios'), ('616', 'Sin obligaciones fiscales'), ('620', 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', 'Régimen de Incorporación Fiscal'), ('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', 'Opcional para Grupos de Sociedades'), ('624', 'Coordinados'), ('625', 'Régimen de las Actividades Empresariales con Ingresos a través de Plataformas Tecnológicas'), ('626', 'Régimen Simplificado de Confianza')], max_length=10)),
                ('uso_cfdi', models.CharField(choices=[('G01', 'Adquisición de mercancías'), ('G02', 'Devoluciones, descuentos o bonificaciones'), ('G03', 'Gastos en general'), ('I01', 'Construcciones'), ('I02', 'Mobilario y equipo de oficina por inversiones'), ('I03', 'Equipo de transporte'), ('I04', 'Equipo de cómputo y accesorios'), ('I05', 'Dados, troqueles, moldes, matrices y herramental'), ('I06', 'Comunicaciones telefónicas'), ('I07', 'Comunicaciones satelitales'), ('I08', 'Otra maquinaria y equipo'), ('D01', 'Honorarios médicos, dentales y gastos hospitalarios'), ('D02', 'Gastos médicos por incapacidad o discapacidad'), ('D03', 'Gastos funerales'), ('D04', 'Donativos'), ('D05', 'Intereses reales efectivamente pagados por créditos hipotecarios'), ('D06', 'Aportaciones voluntarias al SAR'), ('D07', 'Primas por seguros de gastos médicos'), ('D08', 'Gastos de transportación escolar obligatoria'), ('D09', 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones'), ('D10', 'Pagos por servicios educativos (colegiaturas)'), ('S01', 'Sin efectos fiscales'), ('CP01', 'Pagos'), ('CN01', 'Nómina')], max_length=10, verbose_name='Uso CFDI')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('telefono_movil', models.CharField(blank=True, max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre de contacto')),
                ('calle', models.CharField(max_length=200)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento', max_digits=5)),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Americanos'), ('EUR', 'Euros')], default='MXN', max_length=10)),
                ('clasificacion', models.CharField(choices=[('A', 'Clase A (Alto volumen)'), ('B', 'Clase B (Medio volumen)'), ('C', 'Clase C (Bajo volumen)')], default='C', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
