# Generated by Django 5.2.7 on 2026-07-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0008_cotizacionventa_vendedor_facturaventa_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedores_asignados',
            field=models.ManyToManyField(blank=True, related_name='clientes_asignados', to='ventas.vendedor'),
        ),
    ]
