# Generated by Django 5.2.7 on 2026-07-23 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_vendedores_asignados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentario'), ('tarea', 'Tarea Pendiente'), ('evento', 'Evento / Reunión')], default='comentario', max_length=20)),
                ('titulo', models.CharField(help_text='Resumen corto de la actividad', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('es_privado', models.BooleanField(default=True, help_text='Si es True, solo el equipo interno puede verlo.')),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Cliente',
                'verbose_name_plural': 'Actividades de Clientes',
                'ordering': ['-fecha_programada', '-fecha_creacion'],
            },
        ),
    ]
