# Generated by Django 5.2.7 on 2026-07-23 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_actividadcliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rfc', 'RFC / Constancia de Situación Fiscal'), ('contrato', 'Contrato de Servicios'), ('comprobante_domicilio', 'Comprobante de Domicilio'), ('acta_constitutiva', 'Acta Constitutiva'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('archivo', models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG', upload_to='documentos_clientes/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Contrato firmado versión 2024', max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
