# Generated by Django 5.2.7 on 2026-08-13 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_documentocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('especialidad', models.CharField(blank=True, help_text='Ej: Mecánica general, Electricidad, Pintura', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mecanico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mecánico',
                'verbose_name_plural': 'Mecánicos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_servicio', models.CharField(choices=[('MECANICA', '🔧 Mecánica General'), ('LAMINADO_PINTURA', '🎨 Laminado y Pintura'), ('AFINACION', '⚙️ Afinación'), ('FRENOS_SUSPENSION', '🛞 Frenos y Suspensión'), ('SISTEMA_ELECTRICO', '🔌 Sistema Eléctrico'), ('OTRO', '📋 Otro')], default='MECANICA', max_length=30)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('kilometraje_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_DIAGNOSTICO', 'En Diagnóstico'), ('COTIZADA', 'Cotizada'), ('APROBADA', 'Aprobada'), ('EN_REPARACION', 'En Reparación'), ('TERMINADA', 'Terminada'), ('ENTREGADA', 'Entregada'), ('DIAGNOSTICO_RECHAZADO', 'Diagnóstico Rechazado'), ('COTIZACION_RECHAZADA', 'Cotización Rechazada'), ('CANCELADA', 'Cancelada')], default='NUEVA', max_length=30)),
                ('costo_diagnostico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diagnostico_aplicado', models.BooleanField(default=False, help_text='¿Se cobró el costo de diagnóstico?')),
                ('sintoma_cliente', models.TextField(blank=True, help_text='Lo que el cliente reporta', null=True)),
                ('diagnostico_mecanico', models.TextField(blank=True, help_text='Lo que el mecánico encontró', null=True)),
                ('notas_tecnicas', models.TextField(blank=True, help_text='Detalle de lo que se hizo o se hará', null=True)),
                ('subtotal_refacciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque')], max_length=20, null=True)),
                ('garantia_dias', models.PositiveIntegerField(default=30, help_text='Días de garantía sobre la reparación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_servicio', to='clientes.cliente')),
                ('mecanico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='taller.mecanico')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REFACCION', '🔩 Refacción'), ('MATERIAL', '🎨 Material'), ('MANO_OBRA', '👷 Mano de Obra')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taller.ordenservicio')),
            ],
            options={
                'verbose_name': 'Ítem de Orden',
                'verbose_name_plural': 'Ítems de Orden',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTO', '🏍️ Motocicleta'), ('AUTO', '🚗 Automóvil'), ('CAMIONETA', '🛻 Camioneta')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('vin', models.CharField(blank=True, help_text='Número de identificación vehicular (17 caracteres)', max_length=17, null=True)),
                ('cilindrada', models.PositiveIntegerField(blank=True, help_text='En CC, solo para motos', null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones generales del vehículo', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_servicio', to='taller.vehiculo'),
        ),
    ]
