# Generated by Django 5.2.7 on 2026-08-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_movimientoalmacen_fecha'),
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordenservicio',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén de donde se descontará el stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_taller', to='materiales.almacen'),
        ),
        migrations.AddField(
            model_name='itemordenservicio',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Material o refacción utilizada del inventario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_taller', to='materiales.material'),
        ),
        migrations.AlterField(
            model_name='itemordenservicio',
            name='descripcion',
            field=models.CharField(help_text='Descripción detallada (se llena automático si es material)', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemordenservicio',
            name='tipo',
            field=models.CharField(choices=[('REFACCION', '🔩 Refacción'), ('MATERIAL', ' Material'), ('MANO_OBRA', '👷 Mano de Obra')], max_length=20),
        ),
    ]
