# Generated by Django 5.2.7 on 2026-08-13 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_itemordenservicio_almacen_itemordenservicio_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total Pagado'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_DIAGNOSTICO', 'En Diagnóstico'), ('COTIZADA', 'Cotizada'), ('APROBADA', 'Aprobada'), ('EN_REPARACION', 'En Reparación'), ('TERMINADA', 'Terminada'), ('ENTREGADA', 'Entregada'), ('DIAGNOSTICO_RECHAZADO', 'Diagnóstico Rechazado'), ('COTIZACION_RECHAZADA', 'Cotización Rechazada'), ('CANCELADA', 'Cancelada'), ('PAGADA', 'Pagada')], default='NUEVA', max_length=30),
        ),
        migrations.CreateModel(
            name='PagoOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('TRANSFERENCIA', '🏦 Transferencia'), ('TARJETA', '💳 Tarjeta'), ('CHEQUE', ' Cheque'), ('OTRO', '🔹 Otro')], max_length=20, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, help_text='No. de factura, transferencia, cheque, etc.', max_length=100, verbose_name='Referencia')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='taller.ordenservicio', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Pago de Orden',
                'verbose_name_plural': 'Pagos de Órdenes',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
