# Generated by Django 5.2.7 on 2026-09-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_documentocliente'),
        ('taller', '0003_ordenservicio_total_pagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('cilindrada', models.PositiveIntegerField(help_text='Cilindrada en CC')),
                ('vin', models.CharField(help_text='Número de identificación vehicular', max_length=17, unique=True, verbose_name='Número de Serie (VIN)')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('estado', models.CharField(choices=[('NUEVO', ' Nuevo'), ('SEMINUEVO', '♻️ Seminuevo'), ('EXHIBICION', '🏪 En Exhibición'), ('VENDIDO', '✅ Vendido'), ('RESERVADO', '🔒 Reservado')], default='EXHIBICION', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('costo_reparacion_interna', models.DecimalField(decimal_places=2, default=0, help_text='Suma de refacciones y mano de obra usada para repararla', max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moto en Inventario',
                'verbose_name_plural': 'Motos en Inventario',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='es_interna',
            field=models.BooleanField(default=False, help_text='¿Es una reparación para moto de nuestro inventario?'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_servicio', to='taller.vehiculo'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='vehiculo_inventario',
            field=models.ForeignKey(blank=True, help_text='Moto del inventario en reparación interna', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_reparacion', to='taller.vehiculoinventario'),
        ),
    ]
