# Generated by Django 5.2.7 on 2025-10-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='RFC'),
        ),
    ]
