# Generated by Django 5.2.7 on 2025-10-19 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_proveedor_identificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(max_length=100, verbose_name='Factura/Referencia')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_por_pagar', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
