# Generated by Django 5.2.7 on 2025-10-19 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_cuentaporpagar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_pago', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia (comprobante)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.cuentaporpagar')),
            ],
            options={
                'verbose_name': 'Pago de Cuenta por Pagar',
                'verbose_name_plural': 'Pagos de Cuentas por Pagar',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
