# Generated by Django 5.2.7 on 2025-10-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_pagocuentaporpagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='aplica_iva',
            field=models.BooleanField(default=False),
        ),
    ]
