# Generated by Django 5.2.7 on 2025-10-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_detalleordencompra_aplica_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='precio_con_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
