# Generated by Django 5.2.7 on 2025-11-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_detalleordencompra_precio_con_iva'),
        ('flujocaja', '0002_movimientobancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentaporpagar',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujocaja.cuentabancaria', verbose_name='Cuenta Bancaria'),
        ),
    ]
