# Generated by Django 5.2.7 on 2025-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_pagocuentaporpagar_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='notas',
            field=models.TextField(blank=True, help_text='Comentarios', null=True),
        ),
    ]
