# Generated by Django 5.2.7 on 2025-10-23 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0006_detalleordencompra_precio_con_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa mensual en porcentaje (ej: 2.5 para 2.5%)', max_digits=5)),
                ('fecha_desembolso', models.DateField()),
                ('fecha_inicio_pagos', models.DateField()),
                ('frecuencia_pagos', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], max_length=20)),
                ('num_cuotas', models.PositiveIntegerField()),
                ('metodo_calculo', models.CharField(choices=[('frances', 'Método Francés (Cuota Fija)'), ('americano', 'Método Americano (Interés Periódico)')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Crédito con Proveedor',
                'verbose_name_plural': 'Créditos con Proveedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AmortizacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones', to='creditos.creditoproveedor')),
            ],
            options={
                'ordering': ['numero_cuota'],
                'unique_together': {('credito', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_pago', models.DateField()),
                ('referencia_pago', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('amortizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.amortizacioncredito')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
